# Generated by Django 5.0.6 on 2024-06-25 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecap_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('total_incomes', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('total_balance', models.DecimalField(decimal_places=2, default=0, max_digits=50)),
                ('expenses', models.ManyToManyField(blank=True, to='ecap_app.expense')),
                ('incomes', models.ManyToManyField(blank=True, to='ecap_app.income')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
