# Generated by Django 5.0.6 on 2024-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecap_app', '0005_remove_chat_unique_conversation_chat_unique_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(default='other', max_length=100),
            preserve_default=False,
        ),
    ]
