# Generated by Django 5.0.6 on 2024-07-05 13:28

import ecap_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecap_app', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='product',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=ecap_app.models.get_profile_picture_filepath),
        ),
    ]
